### ISSUE TITLE
Registration, Login not working

### ISSUE THREAD

**Issue by ahmadsajid1989** [liamjack/AuthPortal#1]
I have downloaded and configured everything according to your tuts but when registering i got error in console that 400 bad request. also in auth folder i don't see any register method or file to process the request. am i missing something?

**Comment by liamjack** [comment]
An error "400" means that the parameters were incorrect or something went wrong inside the class, normally the class returns an array containing `error` and `message` parameters. Everything is contained in the class (login, registration, activation...) but you need to create the front end "view" for the user to interface with the class.

**Comment by ahmadsajid1989** [comment]
ok, i solved the issue a bit different way.. but thanks for your reply...
